vim.api.nvim_exec("source ~/.config/nvim/plugins.vim", false)
--vim.api.nvim_exec("source ~/.config/nvim/tab_bar.vim", false)
vim.api.nvim_exec("source ~/.config/nvim/basic_config.vim", false)
require("basic_config")
require("keybinds")
require("spellcheck")
require('nvimlspconfig')
require("nerd")
require("tsv")
require("refactor")
