vim.api.nvim_exec("source ~/.config/nvim/plugins.vim", false)
require("keybinds")
require("spellcheck")
vim.api.nvim_exec("source ~/.config/nvim/lsp.vim", false)
require("nerd")
vim.api.nvim_exec("source ~/.config/nvim/tab_bar.vim", false)
vim.api.nvim_exec("source ~/.config/nvim/basic_config.vim", false)
require("basic_config")
require("tsv")
